# Makefile made with reference to https://rahul.gopinath.org/post/2018/09/07/antlr4-cpp-example/

# Info for linking with ANTLR4 runtime
RUNTIME=/usr/local/lib/antlr4-4.9.1/runtime/Cpp
LIBS=$(RUNTIME)/dist/libantlr4-runtime.a
CCARGS=-c -I $(RUNTIME)/runtime/src -I build/src -std=c++14
CCARGS+= -Wall -Wno-attributes -Wno-sign-compare	
LDARGS=-g

# Files generated by ANTLR4
ANTLRGEN=BaseVisitor Lexer Visitor Parser 
OBJS=$(addsuffix .o,$(addprefix build/cparser,$(ANTLRGEN)))
GSOURCES=$(addsuffix .cpp,$(addprefix build/src/cparser,$(ANTLRGEN)))

# Paths for ANTLR4
ANTLRJAR=/usr/local/lib/antlr-4.9.1-complete.jar
ANTLR4=java -jar $(ANTLRJAR)

# Files for parse tree traversal
TREE_SRC_FILES := $(wildcard src/tree/*.cpp)
TREE_OBJ_FILES := $(patsubst src/tree/%.cpp,build/%.o,$(TREE_SRC_FILES))

# Files for code gen
CG_SRC_FILES := $(wildcard src/codegen/*.cpp)
CG_OBJ_FILES := $(patsubst src/codegen/%.cpp,build/%.o,$(CG_SRC_FILES))

###########################################################################################

bin/c_compiler : src/wrapper.sh bin/mainparser
	cp src/wrapper.sh bin/c_compiler
	chmod u+x bin/c_compiler

# Compile parser
bin/mainparser: dir build/mainparser.o antlr4 $(OBJS) $(TREE_OBJ_FILES) $(CG_OBJ_FILES)
	g++ $(LDARGS) build/mainparser.o $(OBJS) $(TREE_OBJ_FILES) $(CG_OBJ_FILES) $(LIBS) -o bin/mainparser	

build/mainparser.o : src/mainparser.cpp antlr4
	g++ $(CCARGS) $< -o $@

antlr4 : build/generated;

# Compile files generated by ANTLR4
build/%.o : build/src/%.cpp
	g++ $(CCARGS) $< -o $@

build/generated: src/cparser.g4
	$(ANTLR4) -Dlanguage=Cpp -no-listener -visitor -package cparser -o build src/cparser.g4
	@touch build/generated

# Compile tree files
build/%.o : src/tree/%.cpp
	g++ $(CCARGS) $< -o $@ 

# Compile codegen files
build/%.o : src/codegen/%.cpp
	g++ $(CCARGS) $< -o $@ 

.precious: $(GSOURCES)

dir :
	mkdir -p build bin

clean :
	rm -rf build
	rm -f bin/*
